version: '3.8'
services:
  db:
    image: postgres:15
    container_name: cmpc_db_prod
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: cmpc_user
      POSTGRES_PASSWORD: cmpc_pass
      POSTGRES_DB: cmpc_books
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: cmpc_backend_prod
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: cmpc_frontend_prod
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  pgdata:
