version: '3.8'
services:
  db:
    image: postgres:15
    container_name: cmpc_db
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: cmpc_user
      POSTGRES_PASSWORD: cmpc_pass
      POSTGRES_DB: cmpc_books
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: cmpc_backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: cmpc_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  pgdata:
